language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install -n

script:
  - vendor/bin/phpspec run -f pretty
  - vendor/bin/behat

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/677fd54fdfe4b680834c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
