gitory:
    private_path: %root_dir%/private/%env%/
    repositories_path: %root_dir%/private/%env%/repositories/
    log:
        cli: %root_dir%/private/%env%/cli.log
        api: %root_dir%/private/%env%/api.log
    db:
        driver: pdo_sqlite
        path: %root_dir%/private/%env%/gitory.db
    lock:
        path: %root_dir%/private/%env%/lock/
